export default function Terms() {
    return (
        <div
            style={{
                minHeight: '100vh',
                backgroundColor: '#fdf6e3',
                padding: '2rem',
                fontFamily: 'Segoe UI, sans-serif',
                color: '#222',
                lineHeight: '1.6',
                maxWidth: '800px',
                margin: '0 auto',
            }}
        >
            <h1 style={{ fontSize: '2rem', fontWeight: 'bold', marginBottom: '1rem' }}>
                Terms of Use
            </h1>

            <p><strong>Effective Date:</strong> June 21, 2025</p>

            <p>
                Welcome to <strong>Semitic World Translator</strong>. By accessing or using our website and services, you agree to be bound by the following Terms of Use. If you do not agree to these terms, please do not use the service.
            </p>

            <h2 style={{ marginTop: '1.5rem' }}>1. Use of the Service</h2>
            <p>
                Our app allows users to translate text into various Arabic dialects using AI. This service is intended for general information, cultural exploration, and educational purposes only.
            </p>
            <ul>
                <li>You agree to use this service lawfully.</li>
                <li>You must not use it to generate, distribute, or promote hate speech, harassment, or misinformation.</li>
                <li>You are responsible for any content you input and any consequences that arise from it.</li>
            </ul>

            <h2 style={{ marginTop: '1.5rem' }}>2. No Guarantee of Accuracy</h2>
            <p>
                Translations are generated by AI and may be imprecise, offensive, or inappropriate in some contexts. We do <strong>not</strong> guarantee the accuracy, reliability, or appropriateness of any result.
                <br />
                <strong>Do not rely on this service for legal, medical, or safety-critical decisions.</strong>
            </p>

            <h2 style={{ marginTop: '1.5rem' }}>3. Intellectual Property</h2>
            <p>
                All content, branding, design, and software in the app are owned by the creators of Semitic World Translator. You may not copy, modify, or redistribute any part of the service without permission.
            </p>

            <h2 style={{ marginTop: '1.5rem' }}>4. Account and Access</h2>
            <p>
                This service does <strong>not</strong> require an account. We reserve the right to restrict access to any user who violates these terms.
            </p>

            <h2 style={{ marginTop: '1.5rem' }}>5. Termination</h2>
            <p>
                We reserve the right to terminate access to the service at our discretion, with or without notice, especially if you violate these terms.
            </p>

            <h2 style={{ marginTop: '1.5rem' }}>6. Changes to the Service</h2>
            <p>
                We may modify, suspend, or discontinue parts or all of the service at any time without notice.
            </p>

            <h2 style={{ marginTop: '1.5rem' }}>7. Jurisdiction</h2>
            <p>
                These Terms are governed by the laws of <strong>Mexico</strong>. Any disputes arising shall be resolved under these laws.
            </p>

            <h2 style={{ marginTop: '1.5rem' }}>8. Contact</h2>
            <p>
                If you have questions or concerns, contact us at:<br />
                <strong>support@semiticworld.com</strong>
            </p>

            <h2 style={{ marginTop: '1.5rem' }}>9. Acceptance</h2>
            <p>
                By using this service, you agree to these Terms of Use. Continued use after changes are posted constitutes acceptance of those changes.
            </p>
        </div>
    );
}
